### ISSUE TITLE
Kevo Plus?

### ISSUE THREAD

**Issue by jer78** [nfarina/homebridge-kevo#1]
Does this require Kevo Plus to work?

**Comment by bondjw07** [comment]
Yeah, that's the only way to unlock without physically touching the lock

**Comment by ineedhungry** [comment]
Whats the context or string for multiple locks?  It always seems to error out that multiple lockers where found.

**Comment by LwsBtlr** [comment]
"lock Front Door" => "[Front Door] Lock not yet discovered; can't set current state."

**Comment by craigaguy** [comment]
The project does not currently support multiple locks. It's listed as a todo in the code :(

Defining only a single lock doesn't get around it because it logs in to mykevo and enumerates the locks in your account.

If I could code I'd have a go at adding multiple lock support :(

**Comment by abouzek** [comment]
In the next month or so I plan on acquiring a second Kevo unit and I'll try to add this support.

**Comment by ineedhungry** [comment]
YAY!

**Comment by abouzek** [comment]
I can't test until I get my Kevo Plus and other Kevo unit but I've adapted this plugin into KevoPlatform which controls a bunch of KevoAccessories. You will have to manually enter each Kevo unit's lock ID into a config.json file but it should work. I'm going on vacation next week so I'll report back mid-late July.

**Comment by ineedhungry** [comment]
The the code in the repo live?  If so ill update and try now.

**Comment by abouzek** [comment]
No, I haven't created a pull request or anything for it yet because I haven't tested it. I'm confident the design is correct but not at all confident it will run yet.

**Comment by ineedhungry** [comment]
I would be happy to try it.

**Comment by abouzek** [comment]
If you can wait until Thursday night I will have my Kevo Plus and can try it out. It will save you headache, I guarantee it.

**Comment by ineedhungry** [comment]
Hahaha alright.  It doesn't matter at this point right now anyway, can't use it with 3 locks right now anyway.

**Comment by craigaguy** [comment]
Awesome :)

Can't wait to try it out.

Craig

**Comment by abouzek** [comment]
#4

**Comment by notasausage** [comment]
This point should really be in the README file. I know it's probably common knowledge for Kevo owners, but I thought having the Homebridge device running in my house on wifi would be enough (and then remembered the lock was Bluetooth and requires that gateway device from Kevo).

**Comment by mr-reamer** [comment]
The app has an option to unlock using BT without physically touching the lock!

Can this not be leveraged? Personally I have a Kevo Plus, but just thought I'd point this out...

**Comment by Tiger519** [comment]
Fair point that Kevo Plus requirement should be specified up front. I have added it to the ReadMe. Also, multiple lock support was added some time ago. Thus I'm going ahead and closing out this issue.
