### ISSUE TITLE
Lock status not updated

### ISSUE THREAD

**Issue by meijerpeter** [nfarina/homebridge-kevo#10]
When opening the Kevo lock with the Kevo app, the status in the Home app is not updated accordingly. In the logs of Homebridge I can see that the status of the lock is according to the Kevo App, but the Home app still shows the old / previous status. Apparently the return value is not set correctly? Anybody experience the same issue? Is it something in the settings perhaps?

**Comment by meijerpeter** [comment]
Hmmm, it does not lock/unlock at all via the Home app. I only can retrieve the correct status of the lock apparently. Any help would be appreciated!

**Comment by fab301s** [comment]
Hmmm, I just checked GitHub for this very reason.  Noticed over the last week or so that the HomeKit status is not updating correctly (and thus sometimes not locking or unlocking).  Kevo app reports the correct status, as does the HomeBridge console:

[9/11/2017, 8:36:51 PM] [Front Door] Login successful.
[9/11/2017, 8:39:23 PM] [Front Door] Getting current state...
[9/11/2017, 8:39:23 PM] [Front Door] Getting current state...
[9/11/2017, 8:39:24 PM] [Front Door] Already logged in.
[9/11/2017, 8:39:24 PM] [Front Door] Already logged in.
[9/11/2017, 8:39:25 PM] [Front Door] Lock status is Locked
[9/11/2017, 8:39:26 PM] [Front Door] Lock status is Locked

Despite the above, HomeKit is reporting the door is unlocked.  I thought it might be related to the iOS11 beta I'm running.  Which version of iOS are you on?

**Comment by meijerpeter** [comment]
Thanks for checking out! I'm on iOS 10.3.3 and having the same issue.

**Comment by fab301s** [comment]
I removed and reinstalled the bridge from my iOS device and uninstalled and reinstalled the Kevo plugin from HomeBridge.  No change unfortunately...

**Comment by meijerpeter** [comment]
Maybe it is something in the code?

**Comment by Tiger519** [comment]
I've had similar intermittent issues. However, it has mostly been issues with Kevo itself. Sometimes the Kevo app doesn't seem to register that the lock has changed states, and there doesn't seem to be any way to force it to refresh.

I think this is related to a similar issue/question I've had (not to hijack the thread but...) where once Kevo DOES recognize a change in state, it doesn't push that state change to Homekit notifications. If I open the Home app (or go to the Homekit screen in control center) the state will update and I'll get the notification (usually). But I'd like to get it on change, regardless if the change happens through HomeKit, like I do with my garage door. When my wife uses her opener in the car, I still get a notification. Not sure if this is a limitation of Kevo itself (I know this is not an official API) or if there is something in the code that could be done to make it work. Not sure if it's possible to have some sort of webhook to listen for state change of the lock and trigger a notification to HomeKit.

**Comment by danieljimenez** [comment]
Yeah I don't see anything triggering a poll of the status in the code. I think we may just need to add that.

**Comment by dishguy** [comment]
this is just for plus or 1st gen as well... if people are getting this error (which I am as well) i wonder if its because i'm using a first gen and not the plus...

**Comment by Tiger519** [comment]
You NEED a Kevo Plus for this to work. This plugin works by essentially logging in to the Kevo website and reading the lock information from there. Without the Kevo Plus, your locks communicate locally by Bluethooth only thus you cannot read the status from the web. I have Kevo 2nd Gen, but I imagine the 1st Gen would work fine too as long as you have Kevo Plus.

**Comment by fab301s** [comment]
It works on a 1st gen (I have one), but you need Kēvo Plus.

**Comment by Tiger519** [comment]
It should be possible to add a status poll, however that should be unnecessary. Every time you reopen the Home app it forces a status poll. With the Kevo API being rather unstable, it may not be the best idea to proactively poll the lock status, especially for people like me that have more than one lock. The only thing this will not get you is notifications when the lock changes state from some other method (manual or even Kevo app, Homekit won't refresh in either case).

I'm closing this issue as there have been no further comments in some time, and I am not able to replicate the issue of not updating at all (i.e. lock status doesn't update proactively, but it does update on opening the Home app as expected).
