### ISSUE TITLE
Basic installation guide - SOLVED *Directions at bottom

### ISSUE THREAD

**Issue by ItsDLite** [nfarina/homebridge-kevo#12]
Could I get some help with this or is it dead? Loaded plugin: homebridge-kevo and installed the two dependencies cheerio and request. Updated homebridge Config.json - homebridge and iOS Home works on my Smartthings applications. But I don't see my lock and can't use it (*Yes I have Kevo Plus) Help Please ~ David

**Comment by Tiger519** [comment]
I'm not familiar with Smartthings. Are you able to get the logs from Homebridge? That could help us figure out where it is failing (login, finding locks, making the get/set Status calls, etc). You shouldn't have had to install either of the dependencies, as they should be automatically installed when you get the plugin.

**Comment by ItsDLite** [comment]
Here is my setup: Raspberry Pi 3 loaded with homebridge. 

Installed homebridge and the homebridge-kevo.

I added the Readme information into the Config.json. I apologize in advance but don't see a log file. I did try and run homebridge in DEBUG mode. But I'm not seeing anything in debug other then the initiation of the plugin for Kēvo. It does however work with my lights in IOS home (but see no lock)

I am a noob and I apologize in advance! Can you past your Config.json? 

Are there any other files I need to edit? Or files that need to be added?

Thanks David

**Comment by Tiger519** [comment]
Would work better if you can post your json here, as well as what you are seeing in homebridge when you initiate. Be sure to redact any personal information/passwords.

**Comment by ItsDLite** [comment]
Okay

**Comment by ItsDLite** [comment]
Here is the complete Config.json file:  (I masked / changed some keys and passwords)

{
"bridge": {
"name": "Homebridge",
"username": "AA:52:A8:35:9F:18",
"port": 51827,
"pin": "031-45-154"
},
"description": "JSON API",
"platforms": [{
"platform": "SmartThings",
"name": "SmartThings",
"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/in$
"app_id": "aaaaaa-bbbb-4586-a010-a445f26c954a",
"access_token": "4062clc8-51e6-1234-a86d-ed59df348aec"
}],
"accessories": [
 {
        "accessory": "Kevo",
        "name": "Front Door",
        "username": "david@aol.com",
        "password": "<KevoPassword>",
        "lock_id": "<cb023123-6ddd-0asd-e8ds-fasdads6885>"
 }
]
}

**Comment by Tiger519** [comment]
Looks like you're missing ", on your app_url line. I would expect that you're getting an invalid config.json error when trying to run Homebridge. But you said you're able to see the Kevo initiation, so I'm not sure if that's your issue or not. Can you paste in what you're seeing in the terminal when trying to run Homebridge?

**Comment by ItsDLite** [comment]
Sorry cut and paste cut that part out:


"bridge": {
"name": "Homebridge",
"username": "D0:02:00:00:00:00",
"port": 51827,
"pin": "031-45-154"
},
"description": "JSON API",
"platforms": [{
"platform": "SmartThings",
"name": "SmartThings",
"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
"app_id": "aaaaaa-bbbb-4586-a010-a445f26c954a",
"access_token": "4062clc8-51e6-1234-a86d-ed59df348aec"
}],
"accessories": [
 {
        "accessory": "Kevo",
        "name": "Front Door",
        "username": "david@aol.com",
        "password": "<Km>",
        "lock_id": "<cb0fghh-fghfgh-fgh-fghfgh-fhgfhgfgh5>"
 }
]
}

**Comment by ItsDLite** [comment]
Here is the initiation: 

pi@raspberrypi:/var/homebridge $ DEBUG=* homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-28 12:35:53] Loaded plugin: homebridge-config-ui
[2018-4-28 12:35:53] Registering platform 'homebridge-config-ui.config'
[2018-4-28 12:35:53] ---
[2018-4-28 12:35:54] Loaded plugin: homebridge-kevo
[2018-4-28 12:35:54] Registering accessory 'homebridge-kevo.Kevo'
[2018-4-28 12:35:54] ---
[2018-4-28 12:35:55] Loaded plugin: homebridge-smartthings
[2018-4-28 12:35:55] Registering platform 'homebridge-smartthings.SmartThings'
[2018-4-28 12:35:55] ---
[2018-4-28 12:35:55] Loaded config.json with 0 accessories and 1 platforms.
[2018-4-28 12:35:55] ---
[2018-4-28 12:35:55] Loading 1 platforms...
[2018-4-28 12:35:55] [SmartThings] Initializing SmartThings platform...
[2018-4-28 12:35:55] [SmartThings] Fetching Smart Things devices.
[2018-4-28 12:35:55] [SmartThings] Refreshing All Device Data
[2018-4-28 12:35:56] [SmartThings] Received All Device Data
[2018-4-28 12:35:56] [SmartThings] Device Added - Group lights, Name Bedroom, ID 2ddfg5-d886-4dgc-abb8-2ddfgdfg75-ddfg6-4fgdc-afdg8-1ddfge8
[2018-4-28 12:35:56] [SmartThings] Device Added - Group lights, Name Pole Lamp, ID 6dfgf7-089a-dfg4-9dfg1-0edfgdgfd9a
[2018-4-28 12:35:56] [SmartThings] Device Added - Group lights, Name Kitchen, ID 3cdg1-bc1f-4cdfg-a97e-4f1dfg0
[2018-4-28 12:35:56] [SmartThings] Device Added - Group switch, Name TV, ID bdfg1d-951d-4dfg-ac47-bf3dfg112
[2018-4-28 12:35:56] [SmartThings] Device Added - Group lights, Name Table Lamp One, ID fadfg3-edfb-4c69-b032-9809dfgfb374
[2018-4-28 12:35:56] [SmartThings] Device Added - Group lights, Name Table Lamp Two, ID 0ddfg4-2f6c-446e-a8fe-5bdfgdgbb5b
[2018-4-28 12:35:56] [SmartThings] Device Added - Group switch, Name lampa, ID 515dfg-41b9-4a0b-b2c2-0dfgdg6c1
[2018-4-28 12:35:56] [SmartThings] Unknown Capabilities: ["Health Check","Light","Notification","Samsung TV"]
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'Bedroom'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'Pole Lamp'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'Kitchen'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'TV'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'Table Lamp One'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'Table Lamp Two'...
[2018-4-28 12:35:56] [SmartThings] Initializing platform accessory 'lampa'...
Setup Payload:
X-HM://0023ISYGGH7C1F
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

  EventedHTTPServer Server listening on port 51827 +0ms
[2018-4-28 12:35:56] Homebridge is running on port 51827.
[2018-4-28 12:35:56] [SmartThings] Direct Connect Is Listening On 10.99.109.107:8000
[2018-4-28 12:35:56] [SmartThings] SmartThings Hub Communication Established

**Comment by ItsDLite** [comment]
Smartthings works fine, HomeBridge just doesn't do anything with Kevo

**Comment by ItsDLite** [comment]
Tiger thank you for trying to help me!

**Comment by ItsDLite** [comment]
NEW UPDATE! I got the accessory finally added! Now I'm experiencing a new issue: 

[2018-4-28 17:00:06] [Door] Error submitting login page: Error: Bad status code 200
[2018-4-28 17:00:06] [Door] There was a problem logging into Kevo. Check your username and password.

Got kevo plus and the webpage works with my login and password. Any ideas?

**Comment by ItsDLite** [comment]
UPDATE:  (* Im now logged into Smartthings and Kevo ... but homebridge locks up after the login was successful. )

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-28 18:10:35] Loaded plugin: homebridge-config-ui
[2018-4-28 18:10:35] Registering platform 'homebridge-config-ui.config'
[2018-4-28 18:10:35] ---
[2018-4-28 18:10:36] Loaded plugin: homebridge-kevo
[2018-4-28 18:10:36] Registering accessory 'homebridge-kevo.Kevo'
[2018-4-28 18:10:36] ---
[2018-4-28 18:10:37] Loaded plugin: homebridge-smartthings
[2018-4-28 18:10:37] Registering platform 'homebridge-smartthings.SmartThings'
[2018-4-28 18:10:37] ---
[2018-4-28 18:10:37] Loaded config.json with 1 accessories and 1 platforms.
[2018-4-28 18:10:37] ---
[2018-4-28 18:10:37] Loading 1 platforms...
[2018-4-28 18:10:37] [SmartThings] Initializing SmartThings platform...
[2018-4-28 18:10:37] [SmartThings] Fetching Smart Things devices.
[2018-4-28 18:10:37] Loading 1 accessories...
[2018-4-28 18:10:37] [FRONT] Initializing Kevo accessory...
[2018-4-28 18:10:37] [SmartThings] Error received type undefined - undefined
[2018-4-28 18:10:37] [SmartThings] Unknown Capabilities: []
Setup Payload:
X-HM://0023ISYWYD107
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2018-4-28 18:10:37] Homebridge is running on port 51827.
[2018-4-28 18:10:37] [SmartThings] Direct Connect Is Listening On 10.99.109.107:8000
[2018-4-28 18:10:38] [FRONT] Login successful.

Then it hangs up ... homebridge not found in iOS Home

**Comment by Tiger519** [comment]
For some reason I'm not finding your new update in the thread, so I'm copying it below:

> NEW UPDATE! I got the accessory finally added! Now I'm experiencing a new issue:
> 
> [2018-4-28 17:00:06] [Door] Error submitting login page: Error: Bad status code 200
> [2018-4-28 17:00:06] [Door] There was a problem logging into Kevo. Check your username and password.
> 
> Got kevo plus and the webpage works with my login and password. Any ideas?

So this is strange indeed. According to the code, you would have already tried to hit the login page, gotten there successfully and not redirected, which means you aren't logged in. Then it tried to submit your login information. When that happens, you should get redirected to the lock status page (code 302), but instead you're getting 200 (OK) which means for some reason it's staying on that page (though it actually goes from mykevo.com/login to mykevo.com/signin, perhaps that can happen with an HTTP 200 message). I hate to be "that guy", but have you checked to make sure your username and password are correct? I think they are case sensitive. Basically this is failing when you are trying to log in to MyKevo, so something has to be off at that step.

**Comment by ItsDLite** [comment]
I've given up! I have attempted to reconfigure my Ras Pi 3 - multiple times. Now I'm stuck on seeing homebridge in the home app but can't join it. I deleted persist / accessories, re-imaged tried different versions of node and nodejs, modified the config.json pin, username, etc. and can't make homegroup work anymore. Thanks for the help Tiger but I'm just not getting anywhere

**Comment by ItsDLite** [comment]
And I got it! Wow... didn't think I ever would. 

Only one question: How to use Siri to unlock the door without unlocking my phone?

Any ideas!

**Comment by Tiger519** [comment]
You cannot do this directly, as Homekit requires your phone to be unlocked to operate any secure devices. This includes if you use any geofencing, by the way. So if you have an automation to unlock your doors when you get home, you will still need to confirm the action on your phone.

The workaround is to create a trigger based automation. I use [homebridge-dummy](https://github.com/nfarina/homebridge-dummy) for this. It creates a stateless switch (will turn on, then automatically back off after a second), which you can use to trigger automations. For example, I created a switches called "Garage Arrival" and "Locks Toggle". I have them set up like so:

`When Garage Arrival turns on, Open the garage door and unlock the garage entry door`
`When Locks Toggle turns on, unlock all of my doors`

So if you have a scene (e.g. my Arriving at Home scene) you can add the switch that drives the automation instead of the device itself. Or alternatively, you can ask Siri to turn on the switch manually e.g. "Turn on the Locks Toggle". Either way, since the switch is not a secure device, it will let you turn it on without unlocking your phone. And the automation will then trigger the secure device.

Just be careful if you use this method with any geofenced automation. The reason this restriction exists is so that you don't inadvertently trigger something (or someone else who has your phone) without you realizing it. Depending on where your house it, it's feasible you could just be driving by and accidentally unlock your door!

**Comment by ItsDLite** [comment]
Thank you for the response Tiger, I found out that the iPhone watch does not block or require the unlocking of my phone. Knowing that I'm now up and running! 

I will keep you method in mind if I want to add the feature. I do plan to still write up directions for others, since this took three days to figure out as a "noob".

Thanks Again for you help!

**Comment by ItsDLite** [comment]
**Basic Setup Guide**
Guide is for a Raspberry Pi 3 (ARM7 chip set):
**REQUIREMENTS:**
Kevo lock
Kevo Plus 
Raspberry Pi 3 (with SD card)
iOS device (iPhone / iPad) – needed to control the lock at home 
Windows computer (*for SSH access to Raspberry Pi via SSH and PuTTy)

**OPTIONAL:** 
iOS device (iPad at least Gen 4 / AppleTV) – needed only for off-site access
Apple Watch - *Hey Siri capabilities for unlocking a device without unlocking your iPad/iPhone
**ASSUMPTIONS:**
You already have Kevo and Kevo plus installed and working. 

**LETS START!**
You will first need to flash your SD card with Raspbian (I used Raspbian Stretch Lite)

Let’s open this guide for imaging the SD card and using SSH on windows: 
 *STOP using this guide after: 
```
sudo apt-get update
sudo apt-get upgrade
```

http://www.mysmartcave.net/2017/08/25/adding-siri-functionality-to-smartthings-using-a-raspberry-pi-homebridge/
If you followed the guide above, you are able to login into you Raspberry Pi via SSH.

We are now going to jump to this set of directions: 
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi
Starting at the command line:

> `sudo apt-get install git make`


We are using Raspbian so skip down to:

`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

Now skip to:
`sudo apt-get install libavahi-compat-libdnssd-dev`

Now switch guides to: 
https://github.com/nfarina/homebridge/blob/master/README.md
`sudo npm install -g --unsafe-perm homebridge`

If it ERRORS run this: 
```
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /usr/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /usr/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild
```
You should now be able to run Homebridge (*but will ERROR on missing config.json)

Next step is to install the Kevo plugin and config.json
Installing the config.json

```
cd ~/.homebridge
sudo nano config.json
```

```
{
“bridge”: {
“name”: “Homebridge”,
“username”: “DD:22:AA:44:55:66”,
“port”: 51822,
“pin”: “031-45-154”
}
}

```
ALWAYS verify your Config.json here: https://jsonlint.com/
Re-run homebridge and confirm you have a working config.json
Now it’s time to install our Kevo plug-in: 
sudo npm install -g homebridge-kevo

We will also need to modify our config.json one more time
```
cd ~/.homebridge
sudo nano config.json
```

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "DD:22:AA:44:55:66",
		"port": 51822,
		"pin": "031-45-154"
	},

	"accessories": [{
		"accessory": "Kevo",
		"name": "FRONT",
		"username": "your-email-address-for-kevo@gmail.com",
		"password": "your-password",
		"lock_id": "your-lock-id"
	}]
}
```
Save your config.json:

```
Ctrl+O
Enter key
Ctrl+X
```

*Your LOCK ID is easy to get in the iOS kevo app under LOCK INFO you can also get it by omitting it in your config.json as described here:  https://github.com/nfarina/homebridge-kevo

Rerun Homebridge

To setup Homebridge on iOS watch this video starting at: 11:55 (*you have a different plugin so yours will be different) https://www.youtube.com/watch?v=g4Smfn1Q5Qc
You can also follow this guide for iOS setup: http://www.mysmartcave.net/2017/08/25/adding-siri-functionality-to-smartthings-using-a-raspberry-pi-homebridge/

Guide to auto load homebridge on Rasbian boot-up:
https://timleland.com/setup-homebridge-to-start-on-bootup/

For remote offsite access you will need to setup AppleTV or a iPad (*Gen 4 or greater) as a hub!

Hope this helps others!
