### ISSUE TITLE
Multiple lock delay is not working

### ISSUE THREAD

**Issue by Tiger519** [nfarina/homebridge-kevo#14]
I have 4 locks, and I always used to get the appropriate delay when trying to set the status of all of them at once (e.g. my "Good Night" scene which includes locking all my doors). However, lately there has been no delay between the first and second lock command. This doesn't make any sense, as the code hasn't been modified. Yet looking at the timestamps, I can see clearly that the first two of four lock commands happen simultaneously, where the other two are spaced properly at 15 seconds. Any idea how this is possible or how to fix? @abouzek not sure if you are still around and could take a look at this?

**Comment by abouzek** [comment]
Hey @Tiger519, I'm not actively utilizing this project anymore because the Kevo API had some strange quirks I could never quite work out and they also were actively changing the way the API behaved. Sorry :(

**Comment by Tiger519** [comment]
I understand. I don't suppose though you have any insight as to why I'm not getting a delay on the first second lock event? (First and second events occur simultaneously). I don't recall ever having an issue, but it doesn't seem to be working properly anymore. This shouldn't be anything to do with the Kevo API, as it is the timing of SENDING the requests that seems to be the issue. As you were aware, simultaneous calls will result in one (or perhaps both?) of them failing. It just baffles me that the delay isn't applied to the second action even though a lock event is occurring and based on the logs there's no reason that variable wouldn't be incremented on the first one but would on the others.

I was considering setting the "lockeventsoccurring" to 1 as a default instead of 0 to force a delay every time, but I don't understand the code well enough (or the way nodejs handles those delays) to know if that will solve the issue at the expense of 15 seconds, or if that will just cause the simultaneous action to occur at t(0)+15s instead of t(0).

**Comment by abouzek** [comment]
Well, seemingly this block of code:
`setTimeout(function() {
this.log("Setting status to %s", kevoStatus);
this._setLockStatus(kevoStatus, lockStatusCallback);
}.bind(this), this.lockOrder * lockEventSpacing);`
is not getting executed when it should be. Maybe use `console.log` to inspect the value of `lockEventsOccurring` right before that block executes to see if it is zero when it should be >0?

**Comment by Tiger519** [comment]
OK that was very helpful. I actually hadn't seen your edit but looking at lockOrder seems to be the key (I also put a marker to tell me if I was in the 0 or >0 block). What seems to be happening is that the first lock to be processed is not lock 0, but random. I ran this three times and got the following orders:
3, 0, 1, 2
0, 1, 2, 3
2, 0, 1, 3
After reviewing the code again I understand that when there are no events, the command processes immediately. When there is at least one event, the spacing is set up front as lockOrder * lockEventsSpacing. But if lockOrder 0 does not process first, the spacing is set at 0 * lockEventsSpacing, which is 0! That is why it is implementing simultaneously with the "no events occurring" block.

I'm guessing there is no way to force lockOrder 0 to go first? I think this can be simply worked around by forcing all the events through the >0 block by removing the if-else though I don't have much knowledge in js and am not sure where to add the binding and execution delay without that if block of code. I suppose I could just put some always true condition in the if statement (or maybe use the same .bind(this), this.lockOrder * lockEventSpacing); ) code at the end of the else block?

If you could suggest a good way to fix this I would greatly appreciate it :-) Otherwise you have already helped a ton and I think I can kludge together something that will work, though I doubt it will be pretty!

**Comment by abouzek** [comment]
Maybe you could use `lockEventsOccurring * lockEventSpacing` so the first event will have no delay (executing the else block) and if any subsequent events come in they would have a 15 second delay, followed by a 30 second, etc?

**Comment by Tiger519** [comment]
So would I just update the block like below? The addition to else block is in bold. I haven't worked in nodejs much and I'm not really sure how to use bind...

if (lockEventsOccurring > 0) {
      lockEventsOccurring++;
      setTimeout(function() {
        this.log("Setting status to %s", kevoStatus);
        this.log("1+ events. Lock order " + this.lockOrder);
        this._setLockStatus(kevoStatus, lockStatusCallback);
      }.bind(this), this.lockOrder * lockEventSpacing);
    }
    else {
      lockEventsOccurring++;
      this.log("Setting status to %s", kevoStatus);
      this.log("0 events. Lock order " + this.lockOrder);
      this._setLockStatus(kevoStatus, lockStatusCallback);
    }**.bind(this), this.lockOrder * lockEventsSpacing**

Edit: updated to add bold section. And I think this will actually maintain all the lock spacing without adding an extra 15 seconds, it just may cause the "0 events" lock to update after one of the "1+ events" locks, which is totally fine.

Edit 2: Oh I just realized you suggested lockEventsOccurring instead of lockOrder. Even easier :-) I'll give it a shot.

**Comment by Tiger519** [comment]
OK, that worked! Now I just need to figure out how to do a pull request, ha!

In the meantime, anyone using this for multiple locks and feeling competent enough to modify the code on their local, just switch lockOrder for lockEventsOccurring and it will take care of the issue of multiple commands being issues simultaneously.

I'll leave this issue open for now until it's actually fixed in the main branch.

**Comment by Tiger519** [comment]
OK I have the pull request done. It simply replaced lockOrder with lockEventsOccurring. I have this running on my local and it is working fine. @abouzek do you still have write access to the repository and if so can you approve the req? Also, though I'm still learning github and nodejs, I'm very invested in this plugin and I wouldn't mind being given write access to the repository since I plan on using it for the foreseeable future.

**Comment by abouzek** [comment]
@Tiger519 I do not have write access, maybe fork the repo and keep track of the changes there?

**Comment by Tiger519** [comment]
Calling @nfarina, are you able to make me a maintainer of this repository?

**Comment by nfarina** [comment]
Absolutely! Sorry for not chiming in earlier.

**Comment by Tiger519** [comment]
No worries. I've merged the pull request and will now close out this issue.
