### ISSUE TITLE
Switch to the mobile app api

### ISSUE THREAD

**Issue by abl** [nfarina/homebridge-kevo#19]
The mobile apps don't require a captcha for login but require a custom certificate-and-nonce dance.

Anyone else looking in to this?

**Comment by bondjw07** [comment]
The problem here is that there is no real API. This project was put together by inspecting the web calls happening on the website and replicating those calls. Since the mobile app is designed and distributed by them, they are able to bypass the security measures put in place because all calls coming from the app are known to be secure. Unfortunately, we can’t replicate those calls like we can for the mobile app. 

My 2 cents here, I don’t think the folks at Kēvo have any desire to do anything about this. It doesn’t affect them or how their product is working. I think the best bet is to call support and complain as others have described in another thread, and then find a new lock that supports HomeKit out of the box. 😕

**Comment by abl** [comment]
> there is no real API

Yes, there is an API. We don't have a contract for it but it's not too hard to figure out.

> we can't replicate those calls

We can. I took a look with a proxy and some other tools.

It looks like the app generates a Curve25519 keypair and then uses that to seed a pair of certificates by taking the SHA-512 digest of the private key. It's pure luck that I was able to identify Curve25519 key generation; I'm not much of a cryptographer.

As far as the server-side, one starts with:

```
curl -X GET \
  https://tumblerprod.unikey.com/2017092501/SiteUtil/ServerInfo \
  -H 'Accept: application/json' \
  -H 'Accept-Encoding: br, gzip, deflate' \
  -H 'Accept-Language: en-us' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: tumblerprod.unikey.com' \
  -H 'User-Agent: Kwikset/6498.1 CFNetwork/978.0.7 Darwin/18.5.0' \
  -H 'X-device-version: 3.1.9' \
  -H 'X-unikey-context: Mobile' \
  -H 'X-unikey-device-type: 1' \
  -H 'cache-control: no-cache'
```

which yields a couple of public certificates and then you need a nonce:

```
curl -X POST \
  https://tumblerprod.unikey.com/2017092501/Nonces \
  -H 'Accept: application/json' \
  -H 'Accept-Encoding: br, gzip, deflate' \
  -H 'Accept-Language: en-us' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: tumblerprod.unikey.com' \
  -H 'User-Agent: Kwikset/6498.1 CFNetwork/978.0.7 Darwin/18.5.0' \
  -H 'X-device-version: 3.1.9' \
  -H 'X-unikey-context: Mobile' \
  -H 'X-unikey-device-type: 1' \
  -H 'cache-control: no-cache' \
  -H 'content-length: '
```

The nonce comes back in the `X-unikey-nonce` header.

The next call is the hard one. https://tumblerprod.unikey.com/2017092501/Authentications expects a POST of JSON like so:

```
{
    "username": "<email address>",
    "password": "<password>",
    "deviceName": "iPhone11,6",
    "deviceCertificate": "<168 bytes of Base64>"
}
```

in the headers, provide `X-unikey-nonce` and an `X-unikey-cnonce`. The attempts I've made so far fail with `"message": "hmac64 and clientHmac are not the same.",`. There's also an `Authorization` header of the form `Unikey-Application <UUID><Base64 (64 bytes)>` - getting it wrong yields an `Invalid AplicationId` (typo preserved here) error. The UUID remains stable across requests (well, to the same URL, anyways), the Base64 does not, so I'm guessing that's the `hmac64`. Oddly, there seems to be a consistent prefix to the Base64 - paired with each UUID from my various sessions, the prefix varies with the UUID.

Unfortunately all I have access to is an iOS device - I wasn't able to get the Kevo app running in an emulator. If someone is able to dump their certs from a real Android device - or get Kevo running in an emulator and then do the same - it becomes much easier to figure out which algorithms and formats are in play.

**Comment by abl** [comment]
Also, another Kwikset lock uses a similar-sounding cryptosystem:

https://www.amazon.com/ask/questions/Tx3EU1ZOO9DUYQH/ref=ask_ql_ql_al_hza

```
Premis lock uses the standard 128-bit AES encryption and the session-based Station-to-Station
protocol which is encrypted with HKDF-SHA-512 derived keys based on per-session Curve25519
keys. 

- Kwikset · January 5, 2017
```

**Comment by Tiger519** [comment]
Closing since there has been no movement/interest in this since 2019
