### ISSUE TITLE
Error submitting login page

### ISSUE THREAD

**Issue by fpgrenier** [nfarina/homebridge-kevo#2]
Hello,

I'm getting the following errors when initializing the Kevo accessory:

[Front Door] Initializing Kevo accessory...
[Front Door] Error submitting login page: Error: Bad status code 200
[Front Door] There was a problem logging into Kevo. Check your username and password.

My credentials are ok, any idea what could be causing this issue?

Thanks!

**Comment by bondjw07** [comment]
Make sure your credentials work here: https://mykevo.com and that you can lock and unlock your device from that portal.  FYI: The Kevo Plus unit is required

**Comment by ggioe** [comment]
Hi I am also getting this error as fpgrenier and I have the Kēvo plus as we'll as my credentials and code are right. Does this still work. I'm also having an issue with my q but one thing at a time. Any help would be appreciated.

**Comment by Tiger519** [comment]
I've not had any login issues. If you are still experiencing trouble please reopen this issue or create a new one.
