### ISSUE TITLE
Unable to Save config.json

### ISSUE THREAD

**Issue by TerribleITGuy** [nfarina/homebridge-kevo#22]
Hi,

I seem to be unable to save the config.json file. I have attempted to enter my information multiple times, but it never seems to save, therefore, seems to be a broken plugin. 

If anyone has any luck with configuring this, please advise! I am running HOOBs v4.0.71.

Thanks!

**Comment by Tiger519** [comment]
If you are unable to save config.json, that isn't an issue with the plugin. Not sure what OS you are running, but try opening your text editor with elevated permissions (e.g. `sudo nano config.json`). I just installed this plugin in a fresh homebridge installation without issue.
