### ISSUE TITLE
Multiple lock support

### ISSUE THREAD

**Issue by abouzek** [nfarina/homebridge-kevo#4]
I'm working on this now here: https://github.com/abouzek/homebridge-kevo. I will test my changes once I receive my Kevo Plus in 2 days and create a pull request after getting it working. @nfarina can we get this on npm?

**Comment by abouzek** [comment]
Done, but quickly issuing multiple requests to the locks results in only the first request going through. #6

**Comment by cdm94** [comment]
Any word on querying?

**Comment by abouzek** [comment]
What do you mean by querying? See #5 for progress updates.

**Comment by cdm94** [comment]
Querying as far as "is my front door locked" or displaying in the HomeKit app as locked or unlocked. Currently it just says whatever the last sent command was.

**Comment by abouzek** [comment]
As far as I know this functionality should work if you ask Siri. It makes an API call to check the status.

**Comment by cdm94** [comment]
On the read me it says "Currently only supports setting lock state (lock/unlock) and not querying current state (like "Are my doors locked?")." I tried this for myself and it said that my door was unlocked, however it is currently locked.

**Comment by bondjw07** [comment]
Yeah, query won't work at this time because when the lock changes status from somewhere other than HomeKit (i.e. Touching the lock) that action is not updated to HomeKit, thus leaving HomeKit thinking that it is still in the previous state. This is how understand the problem to be at the time.

**Comment by abouzek** [comment]
If it doesn't work, HomeKit might be caching device state. I use an app called Home (not the official iOS 10 one) and it will always ask the service what the state is, which makes an API call and returns the correct state from Kevo's API.

**Comment by ItsDLite** [comment]
Could I get some help with this or is it dead? Loaded plugin: homebridge-kevo and installed the two dependencies cheerio and request. Updated homebridge Config.json - homebridge and iOS Home works on my Smartthings applications. But I don't see my lock and can't use it (*Yes I have Kevo Plus) Help Please ~ David

**Comment by Tiger519** [comment]
This was fixed a while ago (for multiple locks).  I am not experiencing any issue with Siri being able to query status, though sometimes due to the time delay Siri will give up before the status is returned (but if you run this in console or look at the logs, you'll see it is fetching current status). I'm going to go ahead and close this one out since the title issue has already been resolved.
