### ISSUE TITLE
Issuing multiple requests in succession results in only first one being executed

### ISSUE THREAD

**Issue by abouzek** [nfarina/homebridge-kevo#6]
This seems to be a limitation even on Kevo's own website.

**Comment by Tiger519** [comment]
Could this be why I'm getting an HTTP 500 error when opening the Apple Home app, which essentially causes all four of my locks to be queries? Though, I didn't have this issue when I was running homebridge on Windows 10 (it just wouldn't stay connected). Running on RPi Zero W now and I'm running into this every time I open Home, though I don't think I've ever had a single query fail. I reported this in #9 Error getting lock status, but after rereading this and #4 I think it could possibly be related.

**Comment by apwelsh** [comment]
One possibility is that it is related to Avahi.    Windows and Mac use Apple's Bonjour, but linux uses Avahi for multicast DNS.    I have not played with Linux for this, as I am a Mac user (I have plenty of Linux systems, but why use then when I have a Mac server).    And in Mac it works flawlessly for me. And you claim it worked great on Windows too.    Therefore, it makes sense to look at the Avahi config which is on if the few things that changed in the configuration.
  

  
  

  
  
>

**Comment by Tiger519** [comment]
This had already been fixed and was unrelated to the HTTP 500 error (that was during a period of instability of the Kevo API). I made a further improvement to the code handling multiple lock inquiries. You still can't issue commands in quick succession (there is a 15 second delay, so even having 2 locks is probably going to result in Siri telling you she didn't hear back from your devices), however you should no longer have any issues with multiple lock commands (I'm using this with 5 locks now).
