### ISSUE TITLE
[question] Separation of modules

### ISSUE THREAD

**Issue by siburny** [nfarina/homebridge-kevo#7]
Would you be interested in separating Kevo functionality into separate npm module? I want to use this library with different home automation application, but it's tied to "homebridge". We could create a generic Kevo lock library that everyone can "require" in their projects.

What do you think?

**Comment by nfarina** [comment]
I would support this! I don't own a Kevo anymore so I couldn't do that myself but I'm happy to accept a PR for it.

**Comment by siburny** [comment]
I can definitely create a generic library, but I would not be able to integrate it into homebridge - I don't own Apple devices.

**Comment by nfarina** [comment]
I see. Well, it should be straightforward enough to extract the code from this module. Just remove all of the homebridge stuff :)

**Comment by siburny** [comment]
Oh yeah, this is easy :) I just didn't want to send a PR that remove homebridge stuff and break people's projects.

I am also implementing "Q" promise library.
